<?php
/**
 * Implements hook_theme().
 */
function bljo6035_new_theme($existing, $type, $theme, $path) {
  $variables = [
    'new' => [
      'variables' => [
        'text' => NULL,
      ],
      'template' => 'new',
    ],
  ];
  return $variables;
}

function bljo6035_new_getLatestRecipes(): array {
  $nids = \Drupal::entityQuery('node')->condition('status', 1)->condition('type', 'rezept')->execute();
  //$nids = array_slice(array_flip($nids), 0, 3);
  $nids = array_slice($nids, 0, 3);

  return \Drupal\node\Entity\Node::loadMultiple($nids);
}
